// File: lib/firebase_options.dart
// Note: This file is auto-generated by flutterfire, but we are creating it manually for now.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWeb',
    appId: '1:1234567890:web:1234567890',
    messagingSenderId: '1234567890',
    projectId: 'mi-ia-dummy',
    authDomain: 'mi-ia-dummy.firebaseapp.com',
    storageBucket: 'mi-ia-dummy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFjwv9PVSUJK_vQA4rm2igDmxJ2uu4dwE',
    appId: '1:224754781635:android:d6d28165bbd9c45e864176',
    messagingSenderId: '224754781635',
    projectId: 'inventario-b4009',
    storageBucket: 'inventario-b4009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForIOS',
    appId: '1:1234567890:ios:1234567890',
    messagingSenderId: '1234567890',
    projectId: 'mi-ia-dummy',
    storageBucket: 'mi-ia-dummy.appspot.com',
    iosBundleId: 'com.example.miIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForMacOS',
    appId: '1:1234567890:macos:1234567890',
    messagingSenderId: '1234567890',
    projectId: 'mi-ia-dummy',
    storageBucket: 'mi-ia-dummy.appspot.com',
    iosBundleId: 'com.example.miIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWindows',
    appId: '1:1234567890:windows:1234567890',
    messagingSenderId: '1234567890',
    projectId: 'mi-ia-dummy',
    storageBucket: 'mi-ia-dummy.appspot.com',
  );
}